FROM node:lts-alpine

# make the 'kafka-consumer' folder the current working directory
WORKDIR /kafka-consumer2

# copy both 'package.json' and 'package-lock.json' (if available)
COPY kafka-consumer2/package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY kafka-consumer2/. .

EXPOSE 3000
# CMD [ "npm", "start" ]
