FROM node:lts-alpine

# make the 'kafka-producer' folder the current working directory
WORKDIR /kafka-producer

# copy both 'package.json' and 'package-lock.json' (if available)
COPY kafka-producer/package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY kafka-producer/. .

EXPOSE 3001
# CMD [ "npm", "start" ]
